version: "3.9"
services:

  # collector
  collector:
    image: otel/opentelemetry-collector-dev:latest
    ports:
      - "4317:4317"
      - "13133:13133"
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/collector.yaml:ro
    command: [ "--config=/etc/collector.yaml" ]

  petclinic:
    image: petclinic-rest-with-agent
    ports:
      - "9966:9966"
    command: [ "-a", "otel", "--endpoint", "http://collector:4317" ]

