version: "3.9"
services:

  collector:
    build:
      context: ./collector
      dockerfile: Dockerfile
    ports:
      - "4317:4317"
      - "13133:13133"
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/collector.yaml:ro
    command: [ "--config=/etc/collector.yaml" ]

  petclinic:
    build:
      context: .
      dockerfile: Dockerfile-petclinic
    ports:
      - "2022:22"
      - "9966:9966"
#    command: [ "/usr/bin/sshd", "-D", "-e" ]
#    command: [ "-a", "otel", "--endpoint", "http://collector:4317" ]

  testrunner:
    build:
      context: .
      dockerfile: Dockerfile-testrunner
    volumes:
      - ./results:/app/results
    command: ["/app/bin/run-remote-sequence.sh"]

