name: publish-petclinic-base-image
on: workflow_dispatch
jobs:
  push_to_registry:
    name: make spring-petclinic base img
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: push to gh packages
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile-petclinic-base
          tags: ghcr.io/breedx-splk/iguanodon/petclinic-base:latest
