name: publish-petclinic-base-image
on: workflow_dispatch
jobs:
  push_to_registry:
    name: make spring-petclinic base img
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Docker-petclinic-base
#          registry: docker.pkg.github.com
#          repository: breedx-splk/iguanodon/spring-petclinic-base
          tags: breedx-splk/iguanodon/spring-petclinic-base:latest
