name: run-test-sequence
on: workflow_dispatch
jobs:
  overhead-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: docker-build
        run: docker-compose build
      - name: run-test-in-docker-compose
        run: docker-compose up --exit-code-from testrunner
      - name: publish-results
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /github/workspace/results
          destination_dir: web/results
          keep_files: true