name:
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker-compose build
      - name: run-test
        run: docker-compose up --exit-code-from testrunner